version: "3.3"
services:
    # image project
    php:
        build:
            args:
                user: usuario
                uid: 1000
            context: ./docker/php/
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - /home/cloud/public/atualizacaomonetaria:/var/www/storage/app/atualizacaomonetaria
            - /home/cloud/var/tabelas:/var/www/storage/app/tabelas
            - /home/joaobritto/Documentos/teste/tabelas:/var/www/storage/app/teste
        networks:
            - projeto_network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - projeto_network

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'nome_do_bd'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_USER: 'root'
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3389:3306
        networks:
            - projeto_network

networks:
    projeto_network:
        driver: bridge
